export const CourseList = [
	{ code: "COM111", title: "Introduction to Computing" },
	{ code: "COM112", title: "Introduction to Digital Electronics" },
	{ code: "COM113", title: "Introduction to Programming" },
	{ code: "COM114/126", title: "PC Upgrading & Maintenance" },
	{ code: "COM116", title: "Statistics for Computing" },
	{ code: "COM117", title: "Computer Application Packages" },
	{ code: "COM121", title: "Programming Language using Java" },
	{ code: "COM122", title: "Introduction to Internet" },
	{ code: "COM123", title: "Computer Application Packages" },
	{ code: "COM124", title: "Data Structure & Algorithm" },
	{ code: "COM125", title: "Introduction to System Analysis" },
	{ code: "COM127", title: "Programming in C" },
	{ code: "COM128", title: "Introduction to Discrete Mathematics" },
	{ code: "COM212", title: "Introduction to System Programming" },
	{ code: "COM213", title: "Introduction to Unified Modelling Language" },
	{ code: "COM214", title: "File Organization & Management" },
	{ code: "COM215", title: "Computer Application Packages II" },
	{ code: "COM216", title: "Computer System Troubleshooting" },
	{ code: "COM218", title: "Statistics for Computing II" },
	{ code: "COM220", title: "Basic Computer Networking" },
	{ code: "COM221", title: "Programming in Object-Oriented FORTRAN" },
	{ code: "COM222", title: "Seminar on Computer & Society" },
	{ code: "COM223", title: "Basic Hardware Maintenance" },
	{ code: "COM224/217", title: "Management Information System" },
	{ code: "COM225", title: "Web Technology" },
	{ code: "COM226", title: "Computer System Troubleshooting" },
	{ code: "COM227", title: "Introduction To Computer Security" },
	{ code: "COM228", title: "Mobile Application Development" },
	{ code: "COM229", title: "Project" },
	{ code: "EDP126", title: "Introduction To Entrepreneurship" },
	{ code: "GNS101", title: "Use of English I" },
	{ code: "GNS102", title: "Communication in English I" },
	{ code: "GNS111/127", title: "Citizenship Education I" },
	{ code: "GNS201", title: "Use of English II" },
	{ code: "GNS202", title: "Communication in English II" },
	{ code: "MTH111", title: "Logic and Linear Algebra" },
	{ code: "MTH209", title: "Calculus" },
	{ code: "STA111", title: "Descriptive Statistics" },
	{ code: "STA112", title: "Elementary Probability Theory" },
]

export const VenueList = [
	{ venue: "CE", rooms: ["1-1", "1-2", "2-1", "2-2"] },
	{ venue: "CL", rooms: ["1-1", "1-2"] },
	{ venue: "ENVS", rooms: ["1-1", "1-2", "2-1", "2-2"] },
	{ venue: "NESB", rooms: ["0-1", "0-2", "1-1", "1-2", "2-1", "2-2"] },
	{ venue: "ETF", rooms: ["0-1", "0-2"] },
	{ venue: "NFTB", rooms: ["1-1", "1-2", "2-1", "2-2", "3-1", "3-2"] },
	{ venue: "MP Theatre", rooms: [] },
	{ venue: "MP Gallery", rooms: [] },
	{ venue: "MP", rooms: ["0-1", "0-2", "1-1", "1-2"] },
	{ venue: "NBAM", rooms: ["1-1", "1-2"] },
	{ venue: "NB", rooms: ["1", "2", "3", "4", "5", "6"] },
	{ venue: "NSE", rooms: ["0-1", "1-1", "2-1", "2-2"] },
	{ venue: "NSB", rooms: ["0-1", "0-2", "1-1", "1-2", "2-1", "2-2"] },
	{ venue: "NAB", rooms: ["0-1", "0-2", "1-1", "1-2", "2-1", "2-2"] },
	{ venue: "NASB", rooms: ["0-1", "1-1", "2-1", "2-2"] },
]
